spring.application.name=Cricket_Tournament

#JDBC config (Render Environment Variables se uthayega)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cricket}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#jsp pages
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
debug=true
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=DEBUG

#Server port for Render
server.port=${PORT:8080}

#for forget pswrd by otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jitendrasingh07022004@gmail.com
spring.mail.password=bclj jzag xayr wtvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#for payment
razorpay.key.id=rzp_test_TJoaiDl4hCKEpE
razorpay.key.secret=qGo0sf8DEHbDpjDtGjbIFeRZ